#!/bin/sh
rm ~/.cache/thumbnails/normal/* >/dev/null 2>&1
rm ~/.cache/thumbnails/large/* >/dev/null 2>&1
rm ~/.cache/thumbnails/mpv/* >/dev/null 2>&1
rm ~/.local/share/recently-used.xbel >/dev/null 2>&1
rm ~/.config/QtProject.conf >/dev/null 2>&1
rm -rf ~/Downloads/Telegram\ Desktop >/dev/null 2>&1
rm -rf ~/.snap >/dev/null 2>&1
rm -rf ~/.local/share/Trash/* >/dev/null 2>&1
rm ~/.config/obs-studio/logs/* >/dev/null 2>&1
rm ~/.cache/ranger/* >/dev/null 2>&1
rm ~/.local/share/ranger/* >/dev/null 2>&1
rm ~/engine.bin >/dev/null 2>&1
sed -i '/rar/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/zip/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/7z/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/rm/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/mv/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/mkdir/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/rmdir/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/touch/d' ~/.config/zsh/.histfile >/dev/null 2>&1
sed -i '/mpv/d' ~/.config/zsh/.histfile >/dev/null 2>&1
