#!/bin/sh

nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=1'
nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffsetAllPerformanceLevels=100'
nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels=750'
sudo nvidia-smi -pm 1
sudo nvidia-smi -pl 365
sudo nvidia-smi -lgc=2045,2100
